#!/bin/sh

# remember the top-level directory

TOP=`pwd`

# variable definitions (edit as needed)

CONFIGURATION=Configuration
PYTHON_REL=$TOP/bin/python

# includeLinker function - create a ../include symbolic link in the current
# directory and in each subdirectory (and now a ../stylesheet symbolic link
# as well, for MGI 3.1)

includeLinker() {
	# do this directory
	if [ -h include ]; then
		rm include
	fi
	if [ -h stylesheet ]; then
		rm stylesheet
	fi
	if [ ! -d include ]; then
		echo "Linking to include/    in `pwd`"
		ln -s ../include include
	fi
	if [ ! -d stylesheet ]; then
		echo "Linking to stylesheet/ in `pwd`"
		ln -s ../stylesheet stylesheet
	fi

	# then do all subdirectories recursively
	for name in `ls`
	do
		if [ -d $name ]; then
			if [ $name != include ]; then
			    if [ $name != stylesheet ]; then
				if [ $name != CVS ]; then
					cd $name
					(includeLinker)
					cd ..
				fi
			    fi
			fi
		fi
	done
	}

# ensure that the config file exists

if test ! -r $CONFIGURATION
then
	echo "Missing configuration file.  Please create $CONFIGURATION."
	exit 1
fi

# read variables from the config file

exec 4<&0
/usr/local/mgi/live/lib/python/Configuration.py $CONFIGURATION tab > .Configuration.tab
exec < .Configuration.tab
while read name value junk
do
	case "$name" in
		LIBDIRS)
			LIBDIRS=$value;;
		MGIHOME_PATH)
			MGIHOME_PATH=$value;;
		MGIHOME_URL)
			MGIHOME_URL=$value;;
	  PYTHON)
			PYTHON=$value;;
     GROUP)
			GROUP=$value;;
		WI_PATH)
			WI_PATH=$value;;
		[A-z]*)
			;;	# other parms are not needed by Install
	esac
done
exec 0<&4

# make bin directory and add the Python link

if [ ! -d bin ]; then
	echo "Making 'bin' directory in `pwd`"
	mkdir bin
fi
if [ ! -h bin/python ]; then
	cd bin
	echo "Linking to python in `pwd`"
	ln -s $PYTHON python
	cd $TOP
fi

cd www
if [ -h Configuration ]; then
	echo "Making "Configuration" sym link in `pwd`"
		rm Configuration
fi
ln -s ../Configuration Configuration
cd $TOP

# compile python libraries and make sure they're readable

cd lib/python
echo "Compiling libraries in `pwd`"
rm *pyc
$PYTHON -c 'import compileall; compileall.compile_dir(".")'
chgrp www *pyc
chmod 750 *pyc
cd $TOP

# add links to python and the config file from selected directories

for dir in www/nomen www/lists www/support www/submissions admin www/feedback www/submissions/strains www/egul www/other www/KOMP
do
	cd $dir

	if [ -h python ]; then
		rm python
	fi
	ln -s $PYTHON_REL python
   
	cd $TOP
done

# support new-style link to homology.shtml minihome page, by temporarily
# linking to old orthology.shtml version
cd www/homepages/
if [ -h homology.shtml ]; then
	rm homology.shtml
fi
ln -s orthology.shtml homology.shtml
cd $TOP

# process the eGUL links.dat file

cd www/egul/
./install $MGIHOME_URL
cd $TOP

# make the www/include directory and generate any include files

cd www
if [ ! -d include ]; then
	echo "Making 'include' directory in `pwd`"
	mkdir include
fi
cd $TOP/admin
gen_rcd
gen_includes
gen_stats
#gen_includes.py

cd $TOP

# link to the stylesheet downloaded by the WI for its userdocs
# (temporarily disabled until needed)
# cd $TOP/www/stylesheet
# if [ -h mgihome.css ]; then
# 	rm mgihome.css
# fi
# if [ -r mgihome.css ]; then
# 	mv mgihome.css mgihome.css.old
# fi
# ln -s ${WI_PATH}www/userdocs/stylesheet/mgi.css mgihome.css
# cd $TOP

# make sure the www directory is executable by the right group;
# use 'find' to avoid doing a recursive chmod and chgrp, which
# also follow the symbolic links to the python interpreter...

echo "setting permissions in www/ directory..."
find www -type f -print | xargs chmod 750
find www -type f -print | xargs chgrp www
find www -type d -print | xargs chmod 750
find www -type d -print | xargs chgrp www

# add links to the include file directory and the stylesheet directory
# for each directory under www

cd www
includeLinker
cd $TOP

#
# Warranty Disclaimer and Copyright Notice
# 
#  THE JACKSON LABORATORY MAKES NO REPRESENTATION ABOUT THE SUITABILITY OR 
#  ACCURACY OF THIS SOFTWARE OR DATA FOR ANY PURPOSE, AND MAKES NO WARRANTIES, 
#  EITHER EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY AND FITNESS FOR A 
#  PARTICULAR PURPOSE OR THAT THE USE OF THIS SOFTWARE OR DATA WILL NOT 
#  INFRINGE ANY THIRD PARTY PATENTS, COPYRIGHTS, TRADEMARKS, OR OTHER RIGHTS.  
#  THE SOFTWARE AND DATA ARE PROVIDED "AS IS".
# 
#  This software and data are provided to enhance knowledge and encourage 
#  progress in the scientific community and are to be used only for research 
#  and educational purposes.  Any reproduction or use for commercial purpose 
#  is prohibited without the prior express written permission of the Jackson 
#  Laboratory.
# 
# Copyright (c) 1996, 1999, 2002 by The Jackson Laboratory
# All Rights Reserved
#

