#!/bin/sh

# variable definitions (edit as needed)

CONFIGURATION=Configuration
PYTHON_REL=../bin/python
CONFIG_REL=../lib/python/config.pyc

# includeLinker function - create a ../include symbolic link in the current
# directory and in each subdirectory

includeLinker() {
	# do this directory
	if [ -h include ]; then
		rm include
	fi
	if [ ! -d include ]; then
		ln -s ../include include
	fi

	# then do all subdirectories recursively
	for name in `ls`
	do
		if [ -d $name ]; then
			if [ $name -ne include ]; then
				cd $name
				(includeLinker)
				cd ..
			fi
		fi
	done
	}

# ensure that the config file exists

if test ! -r $CONFIGURATION
then
	echo "Missing configuration file.  Please create $CONFIGURATION."
	exit 1
fi

# read variables from the config file

exec 4<&0
exec < $CONFIGURATION
while read name value junk
do
	case "$name" in
		WI_PATH)
			WI_PATH=$value;;
		MGIHOME_PATH)
			MGIHOME_PATH=$value;;
		PYTHON)
			PYTHON=$value;;
		GROUP)
			GROUP=$value;;
		TITLE)
			TITLE=$value;;
		[A-z]*)
			;;	# other parms are not needed by Install
	esac
done
exec 0<&4

# remember the top-level directory

TOP=`pwd`

# make bin directory and add the Python link

if [ ! -d bin ]; then
	mkdir bin
fi
if [ ! -h bin/python ]; then
	cd bin
	ln -s $PYTHON python
	cd $TOP
fi

# output the title as an include file

echo $TITLE > www/include/title.html

# add links to the include directory under all subdirectories of www

for dir in `ls www`
do
	if [ -d $dir ]; then
		cd www/$dir
		if [ -d include ]; then
			rm include
		fi
		ln -s ../include include
		cd $TOP
	fi
done

# compile python libraries and make sure they're readable

cd lib/python
chmod g+w *pyc
rm *pyc
$PYTHON -c 'import compileall; compileall.compile_dir(".")'
chgrp www *pyc
chmod 750 *pyc
cd $TOP

# make sure the www directory is executable by the right group

chmod -R 750 www
chgrp -R www www

# add links to python and the config file from selected directories under www/

for dir in nomen lists support submissions
do
	cd www/$dir

	if [ -h python ]; then
		rm python
	fi
	ln -s ../$PYTHON_REL python

	if [ -h config.pyc ]; then
		rm config.pyc
	fi
	ln -s ../$CONFIG_REL config.pyc

	cd $TOP
done

# add links to the include file for each directory under www

cd www
includeLinker
cd $TOP
