#!/bin/sh

# remember the top-level directory

TOP=`pwd`

# variable definitions (edit as needed)

CONFIGURATION=Configuration
PYTHON_REL=$TOP/bin/python
CONFIG_REL=$TOP/lib/python/config.pyc

# includeLinker function - create a ../include symbolic link in the current
# directory and in each subdirectory

includeLinker() {
	# do this directory
	if [ -h include ]; then
		rm include
	fi
	if [ ! -d include ]; then
		echo "Linking to include/ in `pwd`"
		ln -s ../include include
	fi

	# then do all subdirectories recursively
	for name in `ls`
	do
		if [ -d $name ]; then
			if [ $name != include ]; then
				if [ $name != CVS ]; then
					cd $name
					(includeLinker)
					cd ..
				fi
			fi
		fi
	done
	}

# ensure that the config file exists

if test ! -r $CONFIGURATION
then
	echo "Missing configuration file.  Please create $CONFIGURATION."
	exit 1
fi

# read variables from the config file

exec 4<&0
exec < $CONFIGURATION
while read name value junk
do
	case "$name" in
		WI_PATH)
			WI_PATH=$value;;
		MGIHOME_PATH)
			MGIHOME_PATH=$value;;
		GEN_PATH)
			GEN_PATH=$value;;
		PYTHON)
			PYTHON=$value;;
		GROUP)
			GROUP=$value;;
		[A-z]*)
			;;	# other parms are not needed by Install
	esac
done
exec 0<&4

# make bin directory and add the Python link

if [ ! -d bin ]; then
	echo "Making 'bin' directory in `pwd`"
	mkdir bin
fi
if [ ! -h bin/python ]; then
	cd bin
	echo "Linking to python in `pwd`"
	ln -s $PYTHON python
	cd $TOP
fi

# compile python libraries and make sure they're readable

cd lib/python
echo "Compiling libraries in `pwd`"
rm *pyc
$PYTHON -c 'import compileall; compileall.compile_dir(".")'
$PYTHON -c 'import config'
chgrp www *pyc
chmod 750 *pyc
cd $TOP

# add links to python and the config file from selected directories

for dir in www/nomen www/lists www/support www/submissions admin
do
	cd $dir

	if [ -h python ]; then
		rm python
	fi
	ln -s $PYTHON_REL python

	if [ -h config.pyc ]; then
		rm config.pyc
	fi
	ln -s $CONFIG_REL config.pyc

	cd $TOP
done

# make the www/include directory and generate any include files

cd www
if [ ! -d include ]; then
	echo "Making 'include' directory in `pwd`"
	mkdir include
fi
cd $TOP/admin
gen_includes
cd $TOP

# make sure the www directory is executable by the right group

chmod -R 750 www
chgrp -R www www

# add links to the include file for each directory under www

cd www
includeLinker
cd $TOP

# add link to the GEN product from within the www/GXD directory

cd www/GXD
if [ -h GEN ]; then
	rm GEN
fi
ln -s $GEN_PATH GEN
cd $TOP
