# mblast_wi_utils.py 
# 
# Utility functions used by the MouseBlast Web Interface.
#


# Imports
#########

import os
import string
import httpReader
import sys

# MGI python libraries
import Configuration

# create a config object to read the Configuration file before importing
# remaining mgi libs - see Configuration.py LIBDIRS mechanism
try:
        config = Configuration.Configuration( 'Configuration', 1)
except (IOError, Configuration.error), msg:
        sys.exit('%s: Error reading config file: %s' % (sys.argv[0], msg))

# Functions
###########

### --- BEGIN TOOLBAR SECTION -------------------------------------------- ###

def getWideHeader (title = 'Insert Page Title Here'):
	# Purpose: gets a page header for the given title, for a page not
	#	using the toolbar (needing the MGI logo instead)
	# Returns: string
	# Assumes: nothing
	# Effects: nothing
	# Throws: nothing

	return headerBar (title, do_logo = 1)

def getWideFooter ():
	# Purpose: gets the footer as generated by the Java side of the WI
	# Returns: string
	# Assumes: the Java side of the WI is up and running
	# Effects: reads the footer via an http connection
	# Throws: nothing

	FooterUrl = os.path.join (config['JAVA_WI'], 'WIFetch?page=footer')
	lines, errors = httpReader.getURL (FooterUrl)
	if errors:
		return ''

	# note that HTTP header information is returned as well, so the actual
	# footer begins after the first empty line

	lines = map (string.strip, lines)
	if '' in lines:
		pos = lines.index ('')
		lines = lines[pos+1:]

	return string.join (lines, '\n')

def getToolbar ():
	# Purpose: gets the toolbar as generated by the Java side of the WI
	# Returns: string
	# Assumes: the Java side of the WI is up and running
	# Effects: reads the toolbar via an http connection
	# Throws: nothing

	ToolbarUrl = os.path.join (config['JAVA_WI'], 'WIFetch?page=toolbar')
	lines, errors = httpReader.getURL (ToolbarUrl)
	if errors:
		return ''

	# note that HTTP header information is returned as well, so the actual
	# toolbar begins after the first empty line

	lines = map (string.strip, lines)
	if '' in lines:
		pos = lines.index ('')
		lines = lines[pos+1:]

	return string.join (lines, '\n')


def toolbar ():
	# Purpose: returns the version of the toolbar which is cached as an
	#	include file (if available) or an empty string (if not)
	# Returns: string
	# Assumes: the file (include/toolbar.html) exists
	# Effects: reads from the file system
	# Throws: nothing

	tbPath = os.path.join (config['TOPFULLPATH'],
				'www/include/toolbar.html')
	if not os.path.exists (tbPath):
		return ''
	fp = open (tbPath, 'r')
	lines = fp.readlines()
	fp.close()
	return string.join (lines, '')

### --- END TOOLBAR SECTION ---------------------------------------------- ###

def bodyStart ():
	# Purpose: provides the opening for a WI page, including the toolbar
	#	and leaving the right-hand table cell open.  Most, if not all,
	#	CGI scripts should call header() instead.
	# Returns: string
	# Assumes: nothing
	# Effects: nothing
	# Throws: nothing

	return '<TABLE WIDTH="100%">' + \
		'<TR WIDTH="100%"><TD WIDTH="15%" VALIGN="top">' + \
			toolbar() + \
		'</TD><TD WIDTH="1" BGCOLOR="#888888">&nbsp;' + \
		'</TD><TD WIDTH="*" VALIGN="top">'

def bodyStop ():
	# Purpose: returns the string of HTML needed to properly close the
	#	tags left open by bodyStart().  Most, if not all, CGI scripts
	#	should call footer() instead.
	# Returns: string
	# Assumes: nothing
	# Effects: nothing
	# Throws: nothing

	return "</TD></TR></TABLE>"

### --- BEGIN HEADER / FOOTER SECTION ------------------------------------ ###

black = "#000000"		# define colors for use in HTML
blueDark = "#D0E0F0"

# header string -- fill in Help section, Page Title, Your Input section
HEADER = string.join (
	[
	'<TABLE WIDTH="100%%" BORDER=0 CELLPADDING=2 CELLSPACING=1>',
	' <TR>',
	'  <TD WIDTH="100%%%%" BGCOLOR="%s">' % blueDark,
	'   <TABLE WIDTH="100%%" BORDER=0 CELLPADDING=0 CELLSPACING=0>',
	'    <TR>',
	'     <TD WIDTH="20%%" VALIGN="center" ALIGN="left">',
	'      %s',
	'     </TD>',
	'     <TD WIDTH="60%%" ALIGN="center" VALIGN="center">',
	'      <FONT COLOR="%s" SIZE=5 FACE="Arial,Helvetica">' % black,
	'       %s',
	'      </FONT>',
	'     </TD>',
	'     <TD WIDTH="20%%" VALIGN="center" ALIGN="center">',
	'      %s',
	'     </TD>',
	'    </TR>',
	'   </TABLE>'
	'  </TD>',
	' </TR>',
	'</TABLE>',
	],
	'\n')

# your input section -- fill in MGI Home URL, MGI ID and database date
YOUR_INPUT = string.join (
	[
	'<FONT COLOR="%s" FACE="Arial,Helvetica" SIZE=-1>' % black,
	' <FORM NAME="header">',
	'  <INPUT TYPE="button" BGCOLOR="%s" NAME="yourInput"' % black,
	'''   VALUE="Your Input" onClick='window.open("%sfeedback/feedback_form.cgi?accID=%s&dataDate=%s")'>''',
	' </FORM>',
	'</FONT>',
	],
	'\n')

# help section -- fill in Help Url
HELP = string.join (
	[
	'      <A HREF="%%s"><IMG SRC="%simages/shared/help_large.jpg" ',
	'	 BORDER=0 ',
	'        WIDTH=32 HEIGHT=30></A>',
	],
	'\n') % config['TOPURL']


def yourInputSection (
	your_input	# tuple of (string MGI ID, string database dump date)
	):
	# Purpose: private function - generates the Your Input section of a
	#	web page, according to the given parameter 'your_input'
	# Returns: string
	# Assumes: nothing
	# Effects: nothing
	# Throws: nothing

	if your_input == None:
		return '&nbsp;'
	accID, dbDate = your_input
	return YOUR_INPUT % (config['MGIHOMEURL'], accID, dbDate)


def helpSection (
	helpUrl		# string; URL to the help page for this web page
	):
	# Purpose: private function - generates the Help graphic and link for
	#	a web page, according to the given 'helpUrl'
	# Returns: string
	# Assumes: nothing
	# Effects: nothing
	# Throws: nothing

	if helpUrl == None:
		return '&nbsp;'
	return  HELP % helpUrl


def headerBar (
	dataset_id,		# string; brief ID for the data type
	format = None,		# string; identifies the format of the page
	additional = None,	# string; extra line of info about the page
	your_input = None,	# tuple of (string mgi id, string db date)
	do_logo = None		# if non-None, use MGI logo not help link
	):
	# Purpose: returns the header bar at the top of the WI's right column.
	#	Most, if not all, CGI scripts should call header() instead.
	# Returns: string
	# Assumes: nothing
	# Effects: nothing
	# Throws: nothing

	helpUrl = None
	pageTitle = dataset_id		# default - title is passed in
	pageFormat = ''
	moreInfo = ''

	if HELP_URL.has_key (dataset_id):
		helpUrl = HELP_URL[dataset_id]
	if PAGE_TITLE.has_key (dataset_id):
		pageTitle = PAGE_TITLE[dataset_id]
	if PAGE_FORMAT.has_key (format):
		pageFormat = '<BR>%s' % PAGE_FORMAT[format]
	if additional:
		moreInfo = '<BR><FONT SIZE=-1>%s</FONT>' % additional

	# if we need to use a logo, then put in the MGI logo, otherwise
	# give a link to a help doc if available

	if do_logo:
		left_column = ('<IMG SRC="%simages/shared/mgi_logo.jpg" ' +
			'WIDTH=160 HEIGHT=80>') % config['TOPURL']
	else:
		left_column = helpSection (helpUrl)

	return HEADER % (left_column,
			pageTitle + pageFormat + moreInfo,
			yourInputSection (your_input) )

def header (
	dataset_id,		# string; brief ID for the data type
	format = None,		# string; identifies the format of the page
	additional = None,	# string; extra line of info about the page
	your_input = None,	# tuple of (string mgi id, string db date)
	do_logo = None		# if non-None, use MGI logo not help link
	):
	# Purpose: provides the "header" inside the BODY section of a page,
	#	including both the toolbar and the header row.  must call
	#	footer() at the end to properly close the page.
	# Returns: string
	# Assumes: nothing
	# Effects: nothing
	# Throws: nothing

	return bodyStart() + \
	    headerBar (dataset_id, format, additional, your_input, do_logo)

def footer ():
	# Purpose: returns the standard footer for the WI
	# Returns: empty string
	# Assumes: nothing
	# Effects: nothing
	# Throws: nothing
	# Notes: closes the cell, row, and table that we opened in header()

	return bodyStop()


#####################
#  Main
#####################

TOPURL = config['TOPURL']
MGIHOMEURL = config['MGIHOMEURL']

# maps from the dataset identifier to the URL for its associated help page
HELP_URL = {
        'acc'     : '%suserdocs/accession_help.shtml' % TOPURL,
        'anatdict': '%suserdocs/anatdict_help.shtml' % TOPURL,
        'antigen' : '%suserdocs/antibody_info.shtml#ant' % TOPURL,
        'antibody': '%suserdocs/antibody_info.shtml' % TOPURL,
        'alleles' : '%suserdocs/allele_help.shtml' % TOPURL,
        'contig'  : '%suserdocs/mapping_data.shtml#con' % TOPURL,
        'exp'     : '%suserdocs/expression_help.shtml#sort' % TOPURL,
        'gxd'     : '%suserdocs/gxdindex_help.shtml#results' % TOPURL,
        'homology': '%s/overview.shtml#hom' % MGIHOMEURL,
        'estclone': '%suserdocs/estclone_help.shtml' % TOPURL,
        'go'      : '%suserdocs/GO_help.shtml' % TOPURL,
        'goann'   : '%suserdocs/GO_help.shtml' % TOPURL,
        'marker'  : '%s/overview.shtml#mkr' % MGIHOMEURL,
        'mbib'    : '%s/overview.shtml#ref' % MGIHOMEURL,
        'mlc'     : '%s/overview.shtml#mlc' % MGIHOMEURL,
        'mldp'    : '%s/overview.shtml#map' % MGIHOMEURL,
        'pheno'   : '%s/overview.shtml#mkr' % MGIHOMEURL,
        'probes'  : '%s/overview.shtml#pro' % MGIHOMEURL,
        'rflp'    : '%s/overview.shtml#rflp' % MGIHOMEURL,
        }

# maps from the dataset identifier to the page title
PAGE_TITLE = {
        'acc'     : 'Accession IDs',
        'anatdict': 'Anatomical Dictionary Browser',
        'antigen' : 'Antigens',
        'antibody': 'Antibodies',
        'alleles' : 'Phenotypic Alleles',
        'contig'  : 'Contig',
        'cross'   : 'DNA Mapping Panel Display',
        'exp'     : 'Gene Expression Data',
        'go'      : 'Gene Ontology Browser',
        'gxd'     : 'Gene Expression Literature Index',
        'homology': 'Mammalian Homologies',
        'image'   : 'Images',
        'estclone': 'cDNA Clone Source Data',
        'goann'   : 'Gene Ontology Annotations',
        'marker'  : 'Genes and Markers',
        'mbib'    : 'References',
        'mlc'     : 'Mouse Locus Catalog',
        'mlcomim' : 'Combined Mouse/Human Phenotypes',
        'mldp'    : 'Marker Mapping Data',
        'oxford'  : 'Oxford Grid',
        'pheno'   : 'Phenotype Classifications',
        'probes'  : 'Molecular Probes and Segments',
        'rflp'    : 'Polymorphisms',
        'schema'  : 'MGD Schema Description',
        }

PAGE_FORMAT = {
        'query'  : 'Query',
        'results': 'Query Results',
        'summary': 'Query Results -- Summary',
        'detail' : 'Query Results -- Details',
        'term'   : 'Term Detail',
        }


### --- END HEADER / FOOTER SECTION -------------------------------------- ###
#
# Warranty Disclaimer and Copyright Notice
# 
#  THE JACKSON LABORATORY MAKES NO REPRESENTATION ABOUT THE SUITABILITY OR 
#  ACCURACY OF THIS SOFTWARE OR DATA FOR ANY PURPOSE, AND MAKES NO WARRANTIES, 
#  EITHER EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY AND FITNESS FOR A 
#  PARTICULAR PURPOSE OR THAT THE USE OF THIS SOFTWARE OR DATA WILL NOT 
#  INFRINGE ANY THIRD PARTY PATENTS, COPYRIGHTS, TRADEMARKS, OR OTHER RIGHTS.  
#  THE SOFTWARE AND DATA ARE PROVIDED "AS IS".
# 
#  This software and data are provided to enhance knowledge and encourage 
#  progress in the scientific community and are to be used only for research 
#  and educational purposes.  Any reproduction or use for commercial purpose 
#  is prohibited without the prior express written permission of the Jackson 
#  Laboratory.
# 
# Copyright © 1996, 1999, 2002 by The Jackson Laboratory
# All Rights Reserved
#
