#!./python
import sys
if '.' not in sys.path:
	sys.path.insert (0, '.')

MGI_LIBS = '/usr/local/mgi/live/lib/python'
if MGI_LIBS not in sys.path:
	sys.path.insert (0, MGI_LIBS)

#import config

import Configuration
config = Configuration.get_Configuration ('Configuration', 1)

import homelib
import webshare_lib

import os

def listToFile (str_list, filename):
    print "writing %s" % filename
    fp = open (filename, 'w')
    for item in str_list:
        fp.write ('%s\n' % item)
    fp.close()
    return

def stringToFileNoNL (s, filename):
    #  Ultimately this should replace the stringToFile method
    #  for the current release being driven by an NIH Survey Janan wants
    #  out, we are only using this call for the generation of ftp_url2.html.
    #  This change was authorized by Jill as it would require more testing
    #  to make sure there was no negative affect on all the other URLs,
    #  if all calls to stringToFile went through here.  This method
    #  does not include the NL character that is added in the call stringToFile
    #  makes to listToFile.  This newline character was causing problems in
    #  firefox with seeing the url in the page.
    print "writing %s" % filename
    fp = open (filename, 'w')
    fp.write ('%s' % s)
    fp.close()

    return


def stringToFile (s, filename):
    listToFile ( [s], filename)
    return

INCLUDEDIR = os.path.join(config['MGIHOME_PATH'], 'www/include/')

def createIncludeLink (includeName, fileLoc ) :
# 
# INPUTS: includeName - name of the soft link to be created
#         fileLoc - full path to source file
    filePath = os.path.join(INCLUDEDIR, includeName)
    if os.path.exists(filePath):
        os.system("rm " + filePath)
    os.system("ln -s " + fileLoc + " " + filePath)

def main ():
    listToFile (homelib.banner(), '../www/include/banner.html')
    listToFile (homelib.footer(), '../www/include/footer.html')
    stringToFile (config['WI_URL'], '../www/include/wi_url.html')
    stringToFile ('"%s";' % config['WI_URL'], '../www/include/wi_url2.html')
    stringToFile (config['FTP_URL'], '../www/include/ftp_url.html')
    stringToFile (config['MTB_URL'], '../www/include/mtb_url.html')
    stringToFile (config['MPD_URL'], '../www/include/mpd_url.html')
    #  This version of the ftp_url file is being generated to support a problem
    #  found in the implementation of TR7388.  The newline being written to
    #  the file after the URL was not being handled well via firefox.
    #  To minimize testing requirements Jill Lewis jlewis@informatics.jax.org
    #  authorized the generation of a second ftp_url html file.
    stringToFileNoNL (config['FTP_URL'], '../www/include/ftp_url2.html')
    stringToFile (config['MGIHOME_URL'], \
        '../www/include/mgihome_url.html')
    stringToFile (config['GB_URL'], '../www/include/gb_url.html')
    stringToFile (config['LOCUSLINK_URL'], \
        '../www/include/locuslink_url.html')
    stringToFile (config['RGD_URL'], \
        '../www/include/rgd_url.html')
    stringToFile (config['ENTREZ_URL'], \
        '../www/include/entrez_url.html')
    stringToFile (config['GLOSSARY_URL'], \
        '../www/include/glossary_url.html')
    stringToFile (config['USERDOCS_URL'], \
        '../www/include/userdocs_url.html')
    stringToFile (config['SCHEMA'],\
        '../www/include/schema_url.html')
    stringToFile (config['NAME'],\
        '../www/include/mgiversion.html')
    stringToFile (config['JAVAWI_URL'], \
        '../www/include/java_url.html')
    stringToFile (config['MOUSEBLAST_URL'], \
        '../www/include/mouseblast_url.html')
    stringToFile (config['WKSILVERS_URL'], \
            '../www/include/wksilvers_url.html')        
    stringToFile (config['COOKBOOK_URL'], \
            '../www/include/cookbook_url.html')        
    stringToFile (config['MORSEBOOK_URL'], \
            '../www/include/morsebook_url.html')        
    stringToFile (config['SILVER_URL'], \
            '../www/include/silverbook_url.html')        
    stringToFile (webshare_lib.webshareLookup('mgi_logo'), \
        '../www/include/mgi_logo.html')
    stringToFile (webshare_lib.webshareLookup('help'), \
        '../www/include/help_large.html')
    stringToFile (webshare_lib.webshareLookup('jax_logo'), \
        '../www/include/jax_logo.html')
    stringToFile (webshare_lib.webshareLookup('mgi_logo_small'), \
        '../www/include/mgi_logo_small.html')
    stringToFile (webshare_lib.webshareLookup('new'), \
        '../www/include/new.html')
    stringToFile (webshare_lib.webshareLookup('mgicss'), \
        '../www/include/stylesheet.html')

    # new additions for KOMP

    stringToFile (config['GENBANK_HOME'],
	'../www/include/genbank_home_url.html')
    stringToFile (config['ENSEMBL_HOME'],
	'../www/include/ensembl_home_url.html')
    stringToFile (config['ENTREZGENE_HOME'],
	'../www/include/entrezgene_home_url.html')
    stringToFile (config['KOMP_HOME'],
	'../www/include/komp_home_url.html')
    stringToFile (config['KOMP_NIH'],
	'../www/include/komp_nih_url.html')
    stringToFile (config['IMSR_HOME'],
	'../www/include/imsr_home_url.html')

    # new include file for the faq's
    stringToFile (config['FAQ_URL'],
        '../www/include/faq_url.html')


    #####----- Template Include Files --------#####
    createIncludeLink('templateHead.html', config['MGICONFIG_PATH'] + 'web/templateHead.html')
    createIncludeLink('templateBodyStart.html', config['MGICONFIG_PATH'] + 'web/templateBodyStart.html')
    createIncludeLink('templateBodyStop.html', config['MGICONFIG_PATH'] + 'web/templateBodyStop.html')

    createIncludeLink('templateBlankBodyStart.html', config['MGICONFIG_PATH'] + 'web/templateBlankBodyStart.html')
    createIncludeLink('templateBlankBodyStop.html', config['MGICONFIG_PATH'] + 'web/templateBlankBodyStop.html')


    return

if __name__ == '__main__':
    main()

