#!./python

import config
import homelib
#import SimpleVocab
import webshare_lib

#SimpleVocab.set_sqlFunction (homelib.sql)

def listToFile (str_list, filename):
    print "writing %s" % filename
    fp = open (filename, 'w')
    for item in str_list:
        fp.write ('%s\n' % item)
    fp.close()
    return

def stringToFileNoNL (s, filename):
    #  Ultimately this should replace the stringToFile method
    #  for the current release being driven by an NIH Survey Janan wants
    #  out, we are only using this call for the generation of ftp_url2.html.
    #  This change was authorized by Jill as it would require more testing
    #  to make sure there was no negative affect on all the other URLs,
    #  if all calls to stringToFile went through here.  This method
    #  does not include the NL character that is added in the call stringToFile
    #  makes to listToFile.  This newline character was causing problems in
    #  firefox with seeing the url in the page.
    print "writing %s" % filename
    fp = open (filename, 'w')
    fp.write ('%s' % s)
    fp.close()

    return

def stringToFile (s, filename):
    listToFile ( [s], filename)
    return

def main ():
    listToFile (homelib.banner(), '../www/include/banner.html')
    listToFile (homelib.footer(), '../www/include/footer.html')
    stringToFile (config.lookup ('WI_URL'), '../www/include/wi_url.html')
    stringToFile ('"%s";' % config.lookup ('WI_URL'), '../www/include/wi_url2.html')
    stringToFile (config.lookup ('FTP_URL'), '../www/include/ftp_url.html')
    #  This version of the ftp_url file is being generated to support a problem
    #  found in the implementation of TR7388.  The newline being written to
    #  the file after the URL was not being handled well via firefox.
    #  To minimize testing requirements Jill Lewis jlewis@informatics.jax.org
    #  authorized the generation of a second ftp_url html file.
    stringToFileNoNL (config.lookup ('FTP_URL'), '../www/include/ftp_url2.html')
    stringToFile (config.lookup ('MGIHOME_URL'), \
        '../www/include/mgihome_url.html')
    stringToFile (config.lookup ('TUTORIAL_URL'), \
        '../www/include/tutorial_url.html')
    stringToFile (config.lookup ('GB_URL'), '../www/include/gb_url.html')
    stringToFile (config.lookup ('LOCUSLINK_URL'), \
        '../www/include/locuslink_url.html')
    stringToFile (config.lookup ('RGD_URL'), \
        '../www/include/rgd_url.html')
    stringToFile (config.lookup ('ENTREZ_URL'), \
        '../www/include/entrez_url.html')
    stringToFile (config.lookup ('GLOSSARY_URL'), \
        '../www/include/glossary_url.html')
    stringToFile (config.lookup ('SCHEMA'),\
        '../www/include/schema_url.html')
    stringToFile (config.lookup ('MGI_VER'),\
        '../www/include/mgiversion.html')
    stringToFile (config.lookup ('JAVAWI_URL'), \
        '../www/include/java_url.html')
    stringToFile (config.lookup ('MOUSEBLAST_URL'), \
        '../www/include/mouseblast_url.html')
    stringToFile (config.lookup ('WKSILVERS_URL'), \
            '../www/include/wksilvers_url.html')        
    stringToFile (config.lookup ('COOKBOOK_URL'), \
            '../www/include/cookbook_url.html')        
    stringToFile (config.lookup ('MORSEBOOK_URL'), \
            '../www/include/morsebook_url.html')        
    stringToFile (config.lookup ('SILVER_URL'), \
            '../www/include/silverbook_url.html')        
    stringToFile (webshare_lib.webshareLookup('mgi_logo'), \
        '../www/include/mgi_logo.html')
    stringToFile (webshare_lib.webshareLookup('help'), \
        '../www/include/help_large.html')
    stringToFile (webshare_lib.webshareLookup('jax_logo'), \
        '../www/include/jax_logo.html')
    stringToFile (webshare_lib.webshareLookup('mgi_logo_small'), \
        '../www/include/mgi_logo_small.html')
    stringToFile (webshare_lib.webshareLookup('new'), \
        '../www/include/new.html')
    stringToFile (webshare_lib.webshareLookup('mgicss'), \
        '../www/include/stylesheet.html')

#   vocab = SimpleVocab.PhenoSlimVocab()
#   listToFile (SimpleVocab.getSelectionList (vocab,
#       url = config.lookup('WI_URL') + 'userdocs/phenoslim.shtml'),
#       '../www/include/phenoslim_select.html')
    return

if __name__ == '__main__':
    main()
#
# Warranty Disclaimer and Copyright Notice
# 
#  THE JACKSON LABORATORY MAKES NO REPRESENTATION ABOUT THE SUITABILITY OR 
#  ACCURACY OF THIS SOFTWARE OR DATA FOR ANY PURPOSE, AND MAKES NO WARRANTIES, 
#  EITHER EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY AND FITNESS FOR A 
#  PARTICULAR PURPOSE OR THAT THE USE OF THIS SOFTWARE OR DATA WILL NOT 
#  INFRINGE ANY THIRD PARTY PATENTS, COPYRIGHTS, TRADEMARKS, OR OTHER RIGHTS.  
#  THE SOFTWARE AND DATA ARE PROVIDED "AS IS".
# 
#  This software and data are provided to enhance knowledge and encourage 
#  progress in the scientific community and are to be used only for research 
#  and educational purposes.  Any reproduction or use for commercial purpose 
#  is prohibited without the prior express written permission of the Jackson 
#  Laboratory.
# 
# Copyright (c) 1996, 1999, 2002 by The Jackson Laboratory
# All Rights Reserved
#

